<div id="accordion">
  <h3>1. Set The Stage</h3>
  <div>
    <p>
    Hello World
  </div>
  <h3>2. Gather Data</h3>
  <div>
    <p>
    Hello World
    </p>
  </div>
  <h3>3. Generate Insights</h3>
  <div>
    <p>
    Hello World
    </p>
  </div>
  <h3>4. Decide What To Do</h3>
  <div>
    <p>
    Hello World
    </p>
  </div>
  <h3>5. Close Retrospective</h3>
  <div>
    <p>
    Hello World
    </p>
  </div>
</div>