<html>
    <head>
        <title>$title$</title>
        <link rel="stylesheet" href="css/retrospectit.css" type="text/css" />
        <link rel="stylesheet" href="css/vader/jquery-ui-1.10.4.custom.min.css">
        <script src="javascript/jquery-1.10.2.js"></script>
        <script src="javascript/jquery-ui-1.10.4.custom.min.js"></script>
        <script>
            jQuery(function() {
            jQuery( "#accordion" ).accordion({
                collapsible: true
            });
          });
        </script>
    </head>
    <body>
        <div class="heading">
            <h1>$title$</h1>
        </div>
        <div class="body">
            $body$
    </div>
    </body>
</html>