<html>
    <head>
        <title>$title$</title>
        <link rel="stylesheet" href="css/retrospectit.css" type="text/css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/vader/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>
        <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script>
            jQuery(function() {
            jQuery( "#accordion" ).accordion({
                collapsible: true
            });
          });
        </script>
    </head>
    <body>
        <div class="heading">
            <h1>$title$</h1>
        </div>
        <div class="body">
            $body$
    </div>
    </body>
</html>